#!/usr/bin/env python3
"""Generate the browsable diagnostics index from committed run artifacts.

These pages exist so archived `run_summary6` panels can be inspected. They are
deliberately NOT the curated Results page: the evidence contract keeps raw
diagnostics off that page, and this generator upholds the same boundary by
excluding every `provenance_only` archive named in the manifest.

No regime labels are printed. A 2026-08 audit found 16 archived
`classification` fields still carry a pre-correction cubic coefficient, so
those fields are not trustworthy for display; the corrected values live in
Paper III. Only parameters, mode and threshold are shown, all of which are
unaffected.

Run with --check to fail when the committed pages differ from a fresh
generation, so the generated files are never hand-edited.
"""
from __future__ import annotations

import argparse
import json
import pathlib
import sys
from collections import defaultdict

ROOT = pathlib.Path(__file__).resolve().parents[1]
RESULTS = ROOT / "docs" / "results"
OUT_DIR = ROOT / "docs" / "diagnostics"
INDEX_JSON = ROOT / "docs" / "data" / "paper-iii-diagnostics.json"
MANIFEST = ROOT / "docs" / "data" / "paper-iii-manifest.json"

BANNER = (
    '!!! warning "Diagnostic archive — not quantitative evidence"\n'
    "    These are raw solver diagnostics kept for inspection and provenance.\n"
    "    They are **not** reader-facing evidence and must not be cited for\n"
    "    quantitative claims. The curated, validated figures live on the\n"
    "    [Results page](../results/index.md). Archives marked provenance-only\n"
    "    in the evidence manifest are excluded here.\n"
)

GENERATED = (
    "<!-- generated by scripts/build_diagnostics_index.py — do not edit by hand -->"
)


def provenance_only() -> set[str]:
    entries = json.loads(MANIFEST.read_text()).get("provenance_only", [])
    return {e["raw_path"] for e in entries}


def collect() -> dict:
    skip = provenance_only()
    families: dict[str, list] = defaultdict(list)
    for plan in sorted(RESULTS.rglob("run_plan.json")):
        case = plan.parent
        rel_repo = str(case.relative_to(ROOT))
        if rel_repo in skip:
            continue
        panels = sorted(p for p in case.glob("runs/*/run_summary6.png"))
        if not panels:
            continue
        const = json.loads((case / "constants.json").read_text())
        nested = const.get("bifurcation") if isinstance(const.get("bifurcation"), dict) else {}
        nested = nested or {}
        rel_results = case.relative_to(RESULTS)
        family = "/".join(rel_results.parts[:2])
        families[family].append({
            "case": str(rel_results),
            "name": rel_results.name,
            "n0": const.get("n0", nested.get("n0")),
            "chi_star": const.get("chi_star", nested.get("chi_star_mode_n0")),
            "panels": [str(p.relative_to(RESULTS)) for p in panels],
        })
    return dict(sorted(families.items()))


def slug(family: str) -> str:
    return family.replace("/", "-")


def render_family(family: str, cases: list) -> str:
    total = sum(len(c["panels"]) for c in cases)
    lines = [
        GENERATED,
        f"# Diagnostics — `{family}`",
        "",
        BANNER,
        "",
        f"{len(cases)} case(s), {total} panel(s).",
        "",
    ]
    for c in cases:
        chi = f"{c['chi_star']:.4f}" if isinstance(c["chi_star"], (int, float)) else "n/a"
        lines += [
            f'??? example "`{c["name"]}` · n₀={c["n0"]} · χ\\*={chi} · {len(c["panels"])} panels"',
            "",
        ]
        for p in c["panels"]:
            run = pathlib.PurePosixPath(p).parent.name
            lines += [f"    **{run}**", "", f"    ![{run}](../results/{p})", ""]
    return "\n".join(lines) + "\n"


def render_index(families: dict) -> str:
    n_cases = sum(len(v) for v in families.values())
    n_panels = sum(len(c["panels"]) for v in families.values() for c in v)
    lines = [
        GENERATED,
        "# Diagnostic archive",
        "",
        BANNER,
        "",
        f"{n_panels} solver diagnostic panels across {n_cases} archived cases.",
        "",
        "Each panel is the simulator's own `run_summary6` output for one run and",
        "is committed alongside the `run.npz` it summarises, so every panel is",
        "reproducible from the archive.",
        "",
        "Regime labels are intentionally omitted: a 2026-08 audit",
        "(`codes/audit_archived_constants.py` in the manuscript repository) found",
        "that some archived `classification` fields predate a correction to the",
        "cubic coefficient. Parameters, mode and threshold are unaffected and are",
        "shown; the corrected coefficients are published in Paper III.",
        "",
        "| family | cases | panels |",
        "|---|---:|---:|",
    ]
    for family, cases in families.items():
        n = sum(len(c["panels"]) for c in cases)
        lines.append(f"| [`{family}`]({slug(family)}.md) | {len(cases)} | {n} |")
    lines += [
        "",
        "A machine-readable index is published at",
        "[`../data/paper-iii-diagnostics.json`](../data/paper-iii-diagnostics.json).",
        "",
    ]
    return "\n".join(lines) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if committed pages differ from a fresh generation")
    args = ap.parse_args()

    families = collect()
    pages = {OUT_DIR / "index.md": render_index(families)}
    for family, cases in families.items():
        pages[OUT_DIR / f"{slug(family)}.md"] = render_family(family, cases)
    payload = json.dumps(
        {"families": families,
         "panel_count": sum(len(c["panels"]) for v in families.values() for c in v)},
        indent=2, sort_keys=True) + "\n"

    if args.check:
        stale = [p.name for p, body in pages.items()
                 if not p.exists() or p.read_text() != body]
        if not INDEX_JSON.exists() or INDEX_JSON.read_text() != payload:
            stale.append(INDEX_JSON.name)
        if stale:
            print("FAIL: diagnostics pages are stale, regenerate: " + ", ".join(stale))
            return 1
        print("OK: diagnostics pages match a fresh generation")
        return 0

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    for path, body in pages.items():
        path.write_text(body)
    INDEX_JSON.write_text(payload)
    print(f"wrote {len(pages)} page(s) and {INDEX_JSON.name}: "
          f"{sum(len(c['panels']) for v in families.values() for c in v)} panels, "
          f"{sum(len(v) for v in families.values())} cases")
    return 0


if __name__ == "__main__":
    sys.exit(main())
